var Course = [
    {
        "id": 211,
        "CourseName": "English 1st Paper Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/6sSqH2z/01.png',
        "img2" : '../images/Edit Your CV.png',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 35, 
    },
    {
        "id": 212,
        "CourseName": "English 2nd paper Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/Kx91vch/Content-Advertising-Social-IMC.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 40, 
    },
    {
        "id": 213,
        "CourseName": "Bangla 1st paper Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/RhtKTsX/English-for-Career-Development.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 45, 
    },
    {
        "id": 214,
        "CourseName": " Bangla 2nd paper Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/805Qtx9/Fron-end-developer.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 50, 
    },
    {
        "id": 215,
        "CourseName": "Math",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/xGD4cKX/Phuthon-Basics.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 55, 
    },
    {
        "id": 216,
        "CourseName": "General Science Course ",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/C5v6dbg/Web-Developer.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 60, 
    },
    {
        "id": 217,
        "CourseName": "HTML Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/6sSqH2z/01.png',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 65, 
    },
    {
        "id": 218,
        "CourseName": "CSS Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/Kx91vch/Content-Advertising-Social-IMC.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 70, 
    },
    {
        "id": 219,
        "CourseName": " Bootstrap Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/RhtKTsX/English-for-Career-Development.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 75, 
    },
    {
        "id": 20,
        "CourseName": "Javascript Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/805Qtx9/Fron-end-developer.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 80, 
    },
    {
        "id": 221,
        "CourseName": " React Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/xGD4cKX/Phuthon-Basics.jpg',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 85, 
    },
    {
        "id": 222,
        "CourseName": "Social Networking Course",
        "CourseBy": "Teacher Name",
        "img" : 'https://i.ibb.co/C5v6dbg/Web-Developer.jpg',
        "img2" : '../../src/images/Edit Your CV.png',
        "email": "masud.md272@gmail.com",
       "code": "45676",
       "price": 90, 
    },
    
          
];

export default Course;